imports:
    - { resource: ../src/Manager/Infrastructure/Symfony/manager-services.yaml }
parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Shared\:
        resource: '../src/Shared/'
        exclude:
            - '../src/Shared/Symfony/Kernel.php'