version: '2'

services:
  phpfpm-node:
    build: './php'
    volumes:
      - ../:/app
      - ./php/custom.ini:/opt/bitnami/php/etc/conf.d/custom.ini
  nginx-node:
    image: 'bitnami/nginx:latest'
    depends_on:
      - phpfpm-node
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/node.conf:/opt/bitnami/nginx/conf/server_blocks/node.conf
      - ../:/app
  database-node:
    image: 'postgres:16'
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: manager-dev
    ports:
      - '5432:5432'
  adminer-node:
    image: adminer
    restart: always
    ports:
      - '8089:8080'

volumes:
  dynamosrcdir:
    name: dynamosrcdir
    external: true