version: '2'

services:
  phpfpm:
    build: './php'
    volumes:
      - ../.:/app
      - ./php/custom.ini.:/opt/bitnami/php/etc/conf.d/custom.ini
  nginx:
    image: 'bitnami/nginx:latest'
    depends_on:
      - phpfpm
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/manager-node.conf:/opt/bitnami/nginx/conf/server_blocks/manager-node.conf
      - ../.:/app
  database:
    image: 'postgres:14'
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: manager-dev
    ports:
      - '5432:5432'
  adminer:
    image: adminer
    restart: always
    ports:
      - '8089:8080'