parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Shared\:
        resource: '../src/Shared/'
        exclude:
            - '../src/Shared/Symfony/Kernel.php'
    App\Manager\Domain\:
        resource: '../src/Manager/Domain/'

    App\Manager\Application\:
        resource: '../src/Manager/Application/'

    App\Manager\Infrastructure\:
        resource: '../src/Manager/Infrastructure/'

    App\Manager\Infrastructure\Symfony\Controller\:
        resource: '../src/Manager/Infrastructure/Symfony/Controller/'
        tags: ['controller.service_arguments']
