imports:
    - { resource: ../../src/Shared/Infrastructure/Oa/Model/common.yaml }

nelmio_api_doc:
    documentation:
        info:
            title: DynamoPHP node
            description: Node API
            version: 1.0.0
        components:
            schemas:
                ValidationErrorList: '%OaValidationErrorList%'
                ValidationError: '%OaValidationError%'
                BusinessError: '%OaBusinessError%'
                TechnicalError: '%OaTechnicalError%'
                BadRequestError: '%OaBadRequestError%'

    areas:
        default:
            path_patterns: [ ^/api ]
        background:
            path_patterns: [ ^/background ]
        manager:
            path_patterns: [ ^/manager ]
        foreground:
            path_patterns: [ ^/foreground ]
