parameters:
  OaLabelSlot:
    description: 'Represent a slot in the ring'
    type: object
    properties:
      id:
        description: 'The unique ID of the slot in the ring'
        type: integer
        minimum: 1
        example: 1
      position:
        description: 'The position of the slot in the ring'
        type: float
        minimum: 0
        maximum: 360
        example: 150
      coverZoneLength:
        description: 'The area, from the position, covered by the slot. For example, given the position 5 and a coverZoneLength of 3, the covered area is [5;8]'
        type: float
        minimum: 0
        maximum: 360
        example: 3
      subDivision:
        description: 'The sub label given to the slot'
        type: string
        example: 'A1'